const $=s=>document.querySelector(s), projects=window.PROJECTS;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const connection=navigator.connection||navigator.mozConnection||navigator.webkitConnection;
const compactOpening=matchMedia('(max-width:700px)').matches||connection?.saveData||/2g/.test(connection?.effectiveType||'');
let stage=0,expanded=false,homeScroll=0,busy=false,opening=0,musicStarted=false,epoch=0;
const bgm=$('#bgm'), music=$('#music-toggle');
const loadImage=img=>{if(!img.dataset.src)return Promise.resolve();img.parentElement?.querySelectorAll('source[data-srcset]').forEach(source=>{source.srcset=source.dataset.srcset;delete source.dataset.srcset});img.src=img.dataset.src;delete img.dataset.src;return img.decode?.().catch(()=>{})||Promise.resolve()};
const loadDeferred=root=>Promise.all([...root.querySelectorAll('img[data-src]')].map(loadImage));
const loadAbout=()=>Promise.all([...$('#about').querySelectorAll('img[data-src]')].filter(img=>!img.closest('#orbit')).map(loadImage));
let openingAssets=Promise.resolve(),openedAssets=Promise.resolve(),aboutAssets=Promise.resolve(),openFallback;
const positions=[['-8%','29%','-16deg'],['9%','8%','-12deg'],['36%','1%','1deg'],['62%','8%','12deg'],['79%','29%','16deg']];
projects.forEach((p,i)=>{const a=document.createElement('a');a.className='project-folder';a.href='#project/'+p.id;a.setAttribute('aria-label','打开项目：'+p.title);a.style.cssText=`--i:${i};--x:${positions[i][0]};--y:${positions[i][1]};--r:${positions[i][2]}`;a.innerHTML=`<img data-src="assets/folder-${p.id}.webp" alt="${p.title}" decoding="async">`;$('#orbit').append(a)});
function updateSteps(){document.querySelectorAll('[data-step]').forEach(e=>e.classList.toggle('active',Number(e.dataset.step)===stage))}
const delay=ms=>new Promise(r=>setTimeout(r,reduced?0:ms));
function syncMusic(){music.setAttribute('aria-pressed',String(!bgm.paused));music.setAttribute('aria-label',bgm.paused?'播放音乐':'暂停音乐');music.querySelector('.music-label').textContent=bgm.paused?'播放音乐':'暂停音乐';music.querySelector('.music-icon').textContent=bgm.paused?'▶':'Ⅱ';music.classList.toggle('playing',!bgm.paused)}
bgm.addEventListener('play',syncMusic);bgm.addEventListener('pause',syncMusic);
function placeMusic(){music.hidden=!musicStarted;if(musicStarted)(!$('#about').hidden&&!$('#home').hidden?$('#music-record'):$('#music-nav')).append(music)}
let fadeTimer;
function startMusic(){if(musicStarted)return;musicStarted=true;if(!bgm.hasAttribute('src')){bgm.src=bgm.dataset.src;delete bgm.dataset.src}bgm.volume=.05;bgm.play().then(()=>{clearInterval(fadeTimer);fadeTimer=setInterval(()=>{bgm.volume=Math.min(.38,bgm.volume+.025);if(bgm.volume>=.38)clearInterval(fadeTimer)},100)}).catch(()=>syncMusic());placeMusic()}
music.onclick=()=>{clearInterval(fadeTimer);if(bgm.paused){bgm.volume=.38;bgm.play().catch(()=>{music.querySelector('.music-label').textContent='点击重试'})}else bgm.pause()};
async function finishOpen(){if(opening!==1)return;opening=2;clearTimeout(openFallback);const e=epoch;$('#tape-video').pause();await Promise.race([openingAssets,new Promise(resolve=>setTimeout(resolve,1600))]);if(e!==epoch)return;busy=false;$('#unbox').hidden=true;$('#angle-open').hidden=false;$('#parcel').className='scene parcel reveal-open';$('#scene-hint').textContent='再次点击箱子，探索包裹。';openedAssets=loadDeferred($('#opened'));$('#angle-open').focus({preventScroll:true})}
$('#unbox').onclick=()=>{if(busy||opening)return;opening=1;busy=true;openingAssets=loadDeferred($('#angle-open'));$('#scene-hint').textContent='撕开封条，让灵感登场。';if(reduced){finishOpen();return}if(compactOpening){$('#unbox').animate([{transform:'none'},{transform:'rotate(-2deg) scale(.98)',offset:.35},{transform:'rotate(1deg) scale(1.02)',offset:.7},{transform:'translateY(-8px) scale(.96)',opacity:0}],{duration:700,easing:'ease-in-out',fill:'forwards'});openFallback=setTimeout(finishOpen,700);return}$('#parcel').classList.add('peeling');const v=$('#tape-video');v.currentTime=0;v.load();openFallback=setTimeout(finishOpen,2200);v.play().catch(finishOpen)};
$('#tape-video').addEventListener('ended',finishOpen);$('#tape-video').addEventListener('error',finishOpen);$('#tape-video').addEventListener('stalled',finishOpen);
$('#angle-open').onclick=async()=>{if(busy)return;busy=true;const e=epoch;aboutAssets=loadAbout();$('#parcel').classList.add('to-overhead');await delay(450);if(e!==epoch)return;$('#angle-open').hidden=true;$('#opened').hidden=false;$('#parcel').className='scene parcel overhead';stage=1;updateSteps();$('#scene-hint').textContent='移到物件上探索，点击唱片机认识我。';await delay(550);if(e!==epoch)return;busy=false;$('#player').focus({preventScroll:true})};
$('#player').onclick=async()=>{if(busy)return;busy=true;const e=epoch;const player=$('#player');player.classList.add('taking-out');await delay(300);if(e!==epoch)return;const disc=document.createElement('img');disc.src=compactOpening?'assets/record-mobile.webp':'assets/record.webp';disc.className='disc-transition';disc.alt='';document.body.append(disc);await delay(420);if(e!==epoch){disc.remove();return}location.hash='about';startMusic();await delay(650);disc.remove();busy=false;player.classList.remove('taking-out')};
function showAbout(){aboutAssets=loadAbout();stage=2;$('#home').hidden=false;$('#project-view').hidden=true;$('#parcel').hidden=true;$('#about').hidden=false;document.body.classList.add('in-about');updateSteps();placeMusic()}
function setExpanded(v){expanded=v;if(v)loadDeferred($('#orbit'));$('#collage').classList.toggle('expanded',v);$('#profile').setAttribute('aria-expanded',v);$('#orbit').inert=!v;$('#orbit').setAttribute('aria-hidden',!v);$('.folder-prompt').innerHTML=v?'收好作品文件夹 <b>↙</b>':'打开我的作品文件夹 <b>↗</b>'}
$('#profile').onclick=()=>setExpanded(!expanded);$('#phone').onclick=()=>{$('#phone').classList.remove('shake');void $('#phone').offsetWidth;$('#phone').classList.add('shake')};$('#phone').onanimationend=()=>$('#phone').classList.remove('shake');
$('#motion').onclick=()=>{const p=document.body.classList.toggle('paused');$('#motion').setAttribute('aria-pressed',p);$('#motion').textContent=p?'继续动效':'暂停动效'};
function reset(){epoch++;clearTimeout(openFallback);opening=0;busy=false;homeScroll=0;stage=0;setExpanded(false);$('#home').hidden=false;$('#project-view').hidden=true;$('#parcel').hidden=false;$('#about').hidden=true;$('#unbox').hidden=false;$('#unbox').getAnimations().forEach(animation=>animation.cancel());$('#opened').hidden=true;$('#angle-open').hidden=true;$('#tape-video').pause();$('#tape-video').currentTime=0;$('#parcel').className='scene parcel waiting';$('#scene-hint').textContent='点击箱子，拆开你的创意包裹。';document.body.classList.remove('in-about');document.querySelectorAll('.disc-transition').forEach(e=>e.remove());updateSteps();placeMusic();scrollTo(0,0)}
$('#restart').onclick=()=>location.hash='';
function openImage(src,alt){$('#lightbox-image').src=src;$('#lightbox-image').alt=alt;$('#lightbox-label').textContent=alt;$('.lightbox-scroll').classList.remove('actual');$('#zoom').textContent='原尺寸';$('#lightbox').showModal()}
$('#read-profile').onclick=()=>openImage('assets/profile.webp','个人信息 · 项目经历与获奖成果');$('#close-lightbox').onclick=()=>$('#lightbox').close();$('#zoom').onclick=()=>{const a=$('.lightbox-scroll').classList.toggle('actual');$('#zoom').textContent=a?'适应屏幕':'原尺寸'};
const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('on-screen',e.isIntersecting)),{rootMargin:'50px'});
function addCharacters(page,src){
 const add=(cls,html)=>{const el=document.createElement('div');el.className='character-scene '+cls;el.innerHTML=html;page.append(el);observer.observe(el)};
 if(src==='project-1-8.webp')add('run-scene','<img class="background-patch" src="assets/run-bg.webp" alt=""><img class="actor runner" src="assets/runner.webp" alt="抱礼盒奔跑的IP">');
 if(src==='project-1-13.webp')add('run13-scene','<img class="background-patch" src="assets/run13-bg.webp" alt=""><span class="run-shadow" aria-hidden="true"></span><img class="actor runner13" src="assets/runner.webp" alt="原地跑动的抱礼盒IP"><span class="run-dashes" aria-hidden="true"></span>');
 if(src==='project-1-12.webp')add('float-scene','<img class="background-patch" src="assets/float-bg.webp" alt=""><img class="actor floater" src="assets/floater-clean.webp" alt="拿着喇叭漂浮的IP"><span class="sound-waves" aria-hidden="true">)))</span>');
 if(src==='project-2-6.webp')add('toys-scene','<div class="toy-cover"></div><img class="toy jessie" src="assets/jessie.webp" alt="翠丝"><img class="toy woody" src="assets/woody.webp" alt="胡迪"><img class="toy buzz" src="assets/buzz.webp" alt="巴斯光年">');
}
function renderProject(p){stage=2;updateSteps();if(!$('#about').hidden)homeScroll=scrollY;observer.disconnect();$('#home').hidden=true;$('#project-view').hidden=false;document.body.classList.remove('in-about');$('#project-title').textContent=p.title;$('#project-number').textContent=`PROJECT 0${p.id} / 05`;$('#project-pages').replaceChildren();const compact=matchMedia('(max-width:700px)').matches;p.pages.forEach((page,i)=>{const el=document.createElement('div');el.className='page-image';el.style.contentVisibility='auto';el.style.containIntrinsicSize='auto 900px';const img=document.createElement('img');if(compact){img.src='assets/'+page.src.replace(/\.webp$/,'-fast.webp')}else{const mobile=page.src.replace(/\.webp$/,'-mobile.webp');img.srcset=`assets/${mobile} 1200w, assets/${page.src} ${page.width}w`;img.sizes='(max-width:1200px) 100vw, 1200px';img.src='assets/'+page.src}img.alt=`${p.title} · 第 ${i+1} 页`;img.width=page.width;img.height=page.height;img.loading=i?'lazy':'eager';img.fetchPriority=i?'low':'high';img.decoding='async';el.append(img);addCharacters(el,page.src);el.querySelectorAll('.character-scene img').forEach(actor=>{actor.loading='lazy';actor.decoding='async';actor.fetchPriority='low'});$('#project-pages').append(el)});document.title=p.title+' · 创意包裹';placeMusic();scrollTo(0,0);$('#project-title').focus({preventScroll:true})}
function route(){const match=location.hash.match(/^#project\/(\d+)$/);if(match){const p=projects.find(p=>p.id===+match[1]);if(p){renderProject(p);return}}if(['#about','#works'].includes(location.hash)){showAbout();if(location.hash==='#works')setExpanded(true);document.title='认识我 · 创意包裹';requestAnimationFrame(()=>scrollTo(0,homeScroll))}else{reset();document.title='拆开我的创意包裹 · 2027 Portfolio'}}
$('#back').onclick=$('#back-bottom').onclick=()=>location.hash='works';addEventListener('hashchange',route);route();
